Add internal command feature

diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -1,49 +1,60 @@
 #!/usr/bin/env bash
 
-DIR=""
-CMD=""
-ARG=""
-OPT=""
+ARG0=""
+ARG1=""
+ARG2=""
+ARG3=""
+ARG4=""
 
-declare -A dirs
+declare -A arg_map
 
 utils::bootstrap() {
-  unset DIR
-  unset CMD
-  unset ARG
-  unset OPT
+  unset ARG0
+  unset ARG1
+  unset ARG2
+  unset ARG3
+  unset ARG4
 
   [[ ! -L "/usr/local/bin/victor" ]] &&
     {
-      ln -s "${HERE}/victor" /usr/local/bin >&2 ||
-        printf '\n%s\n\n' "[ERR]: Invalid persmissions. Run with sudo."
+      ln -s "${HERE}/victor" /usr/local/bin >&2 || {
+        printf '\n%s\n\n' "[WRN]: Invalid persmissions. Run with sudo to symlink as a bin."
+      }
     }
 
   mkdir -p "${HERE}/repos" >&2
 
-  utils::path::map_dirs
+  utils::path::internal_map
+  utils::path::arg_map
 
-  #utils::path::print_lookup
+  # utils::print_lookup
 }
 
 utils::parse_args() {
   while (("$#")); do
-    [[ -z $DIR ]] && DIR="${1}" && shift && continue
-    [[ -z $CMD ]] && CMD="${1}" && shift && continue
-    [[ -z $ARG ]] && ARG="${1}" && shift && continue
-    [[ -z $OPT ]] && OPT="${@}" && break
+    # identical match should be an internal cmd
+    [[ -n "${arg_map["${1}"]}" ]] && ARG0="${1}" &&
+      shift &&
+      [[ -z $ARG4 ]] && ARG4="${@}" &&
+      break
+
+    [[ -z $ARG1 ]] && ARG1="${1}" && shift && continue
+    [[ -z $ARG2 ]] && ARG2="${1}" && shift && continue
+    [[ -z $ARG3 ]] && ARG3="${1}" && shift && continue
+    [[ -z $ARG4 ]] && ARG4="${@}" && break
   done
 }
 
 utils::exec() {
   local here="${HERE}"
-  local -n ref_dirs="dirs"
+  local -n ref_arg_map="arg_map"
 
   utils::parse_args "$@"
-  local -n ref_dir="DIR"
-  local -n ref_cmd="CMD"
-  local -n ref_arg="ARG"
-  local -n ref_opt="OPT"
+  local -n ref_int="ARG0"
+  local -n ref_dir="ARG1"
+  local -n ref_cmd="ARG2"
+  local -n ref_arg="ARG3"
+  local -n ref_opt="ARG4"
 
   # debug prints
   # echo "ref_dir: ${ref_dir}"
@@ -51,19 +62,34 @@ utils::exec() {
   # echo "ref_arg: ${ref_arg}"
   # echo "ref_opt: ${ref_opt}"
 
-  # shift variables
-  # if passed as `dir cmd arg` instead of `dir:cmd arg`
-  [[ ! -z "${ref_arg}" ]] && ref_dir="${DIR}:${CMD}" && ref_cmd="${ARG}"
-
-  local path="${dirs["${ref_dir}", "${ref_cmd}"]}"
+  local path
+  [[ ! -z "${ref_int}" ]] && path="${arg_map["${ref_int}"]}" ||
+    {
+      # shift variables
+      # if passed as `dir cmd arg` instead of `dir:cmd arg`
+      [[ ! -z "${ref_arg}" ]] && ref_dir="${ref_dir}:${ref_cmd}" && ref_cmd="${ref_arg}"
+      path="${arg_map["${ref_dir}", "${ref_cmd}"]}"
+    }
 
   printf '\n%s\n' "[RUN]: "${path}""
-  printf '%s\n\n' "[OPT]: "${ref_opt:=NULL}""
+  printf '%s\n\n' "[ARG4]: "${ref_opt:=NULL}""
 
   "${path}" "${ref_opt}" >&1
 }
 
-utils::path::map_dirs() {
+utils::path::internal_map() {
+  local here="${HERE}"
+  local -a out_f
+
+  local path="${here}/.internal"
+  mapfile -t out_f < <(find "${path}" -maxdepth 1 -mindepth 1 -executable -type f)
+  for f in "${out_f[@]}"; do
+    local key_1=$(basename "${f}")
+    arg_map["${key_1}"]="${f}"
+  done
+}
+
+utils::path::arg_map() {
   local here="${HERE}"
   local -a out_d
   local -a out_f
@@ -78,17 +104,17 @@ utils::path::map_dirs() {
     local key_1=$(echo "${d}" | sed -r 's/\//:/g')
     for f in "${out_f[@]}"; do
       local key_2=$(basename "${f}")
-      dirs["${key_1}", "${key_2}"]="${f}"
+      arg_map["${key_1}", "${key_2}"]="${f}"
     done
   done
 }
 
-utils::path::print_lookup() {
-  local -n ref="dirs"
+utils::print_lookup() {
+  local -n ref="arg_map"
+
+  printf '\n%s\n' "##### ARG2 MAP #####" >&2
   for d in "${!ref[@]}"; do
-    printf 'KEY: %s' "${d}" >&2
-    printf "\n" >&2
-    printf 'VALUE: %s' "${ref["${d}"]}" >&2
-    printf "\n" >&2
+    printf '\n[KEY]: %s\n' "${d}" >&2
+    printf '[RUN]: %s\n\n' "${ref["${d}"]}" >&2
   done
 }
